name: Build and Push Docker Image

on:
  # Trigger on push events to the main branch
  push:
    branches: [ "main" ,"dev"]
  # Trigger on pull request events
  pull_request:
    branches: ["dev"]
    types: [ opened ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Workflow runs on Ubuntu virtual machines

    steps:
          #checkout code

      - name: Checkout
        uses: actions/checkout@v4
      #for multiple platforms
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3    

          # login to own dockerhub 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
        # GitHub Repo->Settings->Secrets then add username and password
        # it should be the same with name here 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #prod image
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        name: master branch image
        working-directory: .
        run: | 
          docker build . --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:prod_${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:prod_${{ github.sha }}  

      # Edge image
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev'}}
        name: edge - dev branch image
        working-directory: .
        run: | 
          docker build . --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:edge
          docker push ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:edge
 
      # PR image
      - if: ${{ github.event_name == 'pull_request' }}
        name: pull request image
        working-directory: .
        run: |
          docker build . --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/git_csv_turso_init:${{ github.sha }}
    
